sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t thanhtamv2t/learn-docker-react .

script:
  - docker run thanthamv2t/learn-docker-react npm run test -- --coverage
