language: node_js
node_js:
  - 10
services:
  - docker

before_install:
  - docker build -t thanhtamv2t/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thanhtamv2t/docker-react npm run test -- --coverage
